# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: shortcode.dev
# email: your-email@example.com
description:  Cheatsheet lists HTML, CSS, Javascript elements, attributes and selectors.  
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://shortcode.dev # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: shortcode
# github_username:  shortcode

# Permalink style 
# Options: https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles
# permalink: none

# incremental: true

host: shortcode

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

highlighter: rouge

sass:
  sass_dir: ./_styles
  style: compressed

theme-colour: '#202943'

collections_dir: collections
collections:
  html:
    output: true
    link: html-cheatsheet
    icon: fab fa-html5
  css:
    output: true
    link: css-cheatsheet
    icon: fab fa-css3-alt
  javascript:
    output: true
    link: javascript-cheatsheet
    icon: fab fa-js-square
  liquid:
    output: true
    link: liquid-cheatsheet
    icon: fas fa-flask
  git:
    output: true
    link: git-cheatsheet
    icon: fab fa-github
  vue:
    output: true
    link: vue-cheatsheet
    icon: fab fa-vuejs
  node:
    output: true
    link: node-cheatsheet
    icon: fab fa-node-js
  cli:
    output: true
    link: cli-cheatsheet
    icon: fas fa-terminal
  markdown:
    output: true
    link: markdown-cheatsheet
    icon: fab fa-markdown
  laravel:
    output: true
    link: laravel-cheatsheet
    icon: fab fa-laravel
  artisan:
    output: true
    link: artisan-cheatsheet
    icon: fab fa-laravel
  blade:
    output: true
    link: blade-cheatsheet
    icon: fab fa-laravel
  wordpress:
    output: true
    link: wordpress-cheatsheet
    icon: fab fa-wordpress-simple
  php:
    output: true
    link: php-cheatsheet
    icon: fab fa-php

defaults:
  - scope:
      type: html
    values:
      layout: code
      type: html
  - scope:
      type: css
    values:
      layout: code
      type: css
  - scope:
      type: javascript
    values:
      layout: code
      type: javascript
  - scope:
      type: liquid
    values:
      layout: code
      type: liquid
  - scope:
      type: git
    values:
      layout: code
      type: git
  - scope:
      type: vue
    values:
      layout: code
      type: vue
  - scope:
      type: node
    values:
      layout: code
      type: node
  - scope:
      type: cli
    values:
      layout: code
      type: cli
  - scope:
      type: markdown
    values:
      layout: code
      type: markdown
  - scope:
      type: laravel
    values:
      layout: code
      type: laravel
  - scope:
      type: artisan
    values:
      layout: code
      type: artisan
  - scope:
      type: blade
    values:
      layout: code
      type: blade
  - scope:
      type: wordpress
    values:
      layout: code
      type: wordpress
  - scope:
      type: php
    values:
      layout: code
      type: php

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - workbox-config.js
  - package-lock.json
  - package.json
